config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "about", to: "about#index"

  get "passwords", to: "passwords#edit", as: :edit_password
  patch "passwords", to: "passwords#update"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "auth/twitter2/callback", to: "omniauth_callbacks#twitter2" 
  # Defines a route that maps HTTP GET requests to the path /auth/twitter2/callback to the OmniauthCallbacksController action twitter2
  
   
  resources :twitter_accounts
  resources :tweets

  root to: "main#index"
  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
    
  end

  def create 
    @user = User.find_by(email: params[:email])
    if @user.present?
      # send email
      PasswordMailer.with(user: @user).reset.deliver_now
    end
      redirect_to root_path, notice: "If an account with that email was found, we have sent a link to reset your password."
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: "password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert: "Your token has expired. Please try again."
  end

  def update
        @user = User.find_signed!(params[:token], purpose: "password_reset")
        if @user.update(password_params)
            redirect_to sign_in_path, notice: "Your password was reset successfully. Please sign in."
        else  
            render :edit,  status: :unprocessable_entity
        end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
<%
=begin%>
 model is required for the following code to work 
<%
=end%>
 <%= render "shared/form_errors", form:form %> 
   <div class="mb-3">
       <%= form.label :password %>
       <%= form.password_field :password, class: "form-control",  placeholder: "Enter password" %>
   </div>
  <div class="mb-3">
       <%= form.label :password_confirmation %>
       <%= form.password_field :password_confirmation, class: "form-control",  placeholder: "Confirm password" %>
   </div>
   <div class="mb-3">
       <%= form.submit "Reset Password", class: "btn btn-primary" %>
   </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot Password</h1>

<%= form_with url: password_reset_path do |form| %>
   <div class="mb-3">
       <%= form.label :email %>
       <%= form.text_field :email, class: "form-control", placeholder: "Enter email" %>
   </div>
   <div class="mb-3">
       <%= form.submit "Reset Password", class: "btn btn-primary" %>
   </div>
<% end %>