config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "about", to: "about#index"

  get "passwords", to: "passwords#edit", as: :edit_password
  patch "passwords", to: "passwords#update"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "auth/twitter2/callback", to: "omniauth_callbacks#twitter2" 
  # Defines a route that maps HTTP GET requests to the path /auth/twitter2/callback to the OmniauthCallbacksController action twitter2
  
   
  resources :twitter_accounts
  resources :tweets

  root to: "main#index"
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: { minimum: 1, maximum: 280 }
  validates :publish_at, presence: true

  after_initialize do
    self.publish_at ||= 24.hours.from_now
  end

  after_save_commit do
    if publish_at_previously_changed?
      TweetJob.set(wait_until: publish_at).perform_later(self)
    end
  end

  def published?
    # adding a questions mark to the end of a method name is a convention in Ruby to indicate that the method returns a boolean value
    tweet_id?
  end

  def publish_to_twitter!
    tweet = twitter_account.client.update(body)
    update(tweet_id: tweet.id)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :require_user_logged_in!
    before_action :set_tweet, only: [:show,:edit, :update, :destroy]
    
    def index
        @tweets = Current.user.tweets
    end

    def new
        @tweet = Tweet.new
    end

      def create
        @tweet = Current.user.tweets.new(tweet_params)
        if @tweet.save
          redirect_to tweets_path, notice: "Tweet was scheduled successfully"
        else
          render :new, status: :unprocessable_entity
        end
    end

    def edit

    end

    def show

    end

    def update
        if @tweet.update(tweet_params)
          redirect_to tweets_path, notice: "Tweet was updated successfully"
        else
          render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @tweet.destroy
        redirect_to tweets_path, notice: "Tweet was unscheduled successfully"
    end

    private

    def tweet_params
      params.require(:tweet).permit(:twitter_account_id, :body, :publish_at)
    end

     def set_tweet
      @tweet = Current.user.tweets.find_by(id: params[:id])
    end
end

app/views/tweets/_form.html.erb
<%= form_with model: @tweet do |form| %>
   <%= render "shared/form_errors", form:form %>
   <div>
      <div class="mb-3">
         <%= form.label :twitter_account_id %>
         <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, { class: "form-control"} %>
         <%= button_to "Connect a Twitter Account", "/auth/twitter2", method: :post, data: {turbo: "false"}, class: "btn btn-primary mt-2" %>
     </div>
     
     <div class="mb-3">
         <%= form.label :body %>
         <%= form.text_area :body,  class: "form-control" %>
     </div>
  
     <div class="mb-3">
         <%= form.label :publish_at %>
         <div class="form-control">
            <%= form.datetime_select :publish_at %>
         </div>
     </div>

     <div class="d-flex gap-2 mb-3">
       <%= form.button "Schedule Tweet", class: "btn btn-primary" %>
       <% if form.object.persisted? %>
          <%= button_to "Delete", form.object, method: :delete, form: {data: {turbo_confirm: "Are you sure?"}}, class: "btn btn-outline-danger" %>
       <% end %>
     </div>

  
   </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="mb-3 card card-body">
   <%= tweet.body %>
   <div class="me-4">
      <%= image_tag tweet.twitter_account.image, class:"rounded-circle " %>
      <%= link_to "#{tweet.twitter_account.name}" , "https://tweet.com/#{tweet.twitter_account.username}", target: :_blank %>

      <% if tweet.published? %>
         <%= link_to "View Tweet","https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}", terget: :_blank %>
      <% else %>
         Scheduled for <%= l tweet.publish_at, format: :long %>
         <%= link_to "Edit Tweet", edit_tweet_path(tweet)%>
          <%
=begin%>
 <%= link_to "Unschedule Tweet", tweet, method: :delete, form: {data: {turbo_confirm: "Are you sure?"}} %> 
<%
=end%>
      <% end %>
   </div>
</div>

app/views/tweets/edit.html.erb
<div class="d-flex align-items-center justify-content-between">
   <h1>Edit Scheduled Tweet</h1>
    <%= link_to "Back to tweets", tweets_path, class: "btn btn-primary" %>
</div>

<%= render "form", tweet: @tweet %>

app/views/tweets/index.html.erb
<div class="d-flex align-items-center justify-content-between">
   <h1>Tweets</h1>
   <% if Current.user.twitter_accounts.any?%>
      <%= link_to "Schedule a Tweet", new_tweet_path, class: "btn btn-primary" %>
   <% end %>
</div>

<% if Current.user.twitter_accounts.none?%>
    <%= button_to "Connect a Twitter Account", "/auth/twitter2", method: :post, data: {turbo: "false"}, class: "btn btn-primary" %>
<% end %>

<%= render @tweets %>

app/views/tweets/new.html.erb
<div class="d-flex align-items-center justify-content-between">
   <h1>Schedule a Tweet</h1>
    <%= link_to "Back to tweets", tweets_path, class: "btn btn-primary" %>
</div>

<%= form_with model: @tweet do |form| %>
   <%= render "shared/form_errors", form:form %>
   <div>
      <div class="mb-3">
         <%= form.label :twitter_account_id %>
         <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, { class: "form-control"} %>
         <%= button_to "Connect a Twitter Account", "/auth/twitter2", method: :post, data: {turbo: "false"}, class: "btn btn-primary mt-2" %>
     </div>
     
     <div class="mb-3">
         <%= form.label :body %>
         <%= form.text_area :body,  class: "form-control" %>
     </div>
  
     <div class="mb-3">
         <%= form.label :publish_at %>
         <div class="form-control">
            <%= form.datetime_select :publish_at %>
         </div>
     </div>

     <div class="mb-3">
       <%= form.button "Schedule Tweet", class: "btn btn-primary" %>
     </div>
   </div>
<% end %>

 