config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "about", to: "about#index"

  get "passwords", to: "passwords#edit", as: :edit_password
  patch "passwords", to: "passwords#update"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "auth/twitter2/callback", to: "omniauth_callbacks#twitter2" 
  # Defines a route that maps HTTP GET requests to the path /auth/twitter2/callback to the OmniauthCallbacksController action twitter2
  
   
  resources :twitter_accounts
  resources :tweets

  root to: "main#index"
  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
   <div class="alert alert-info mt-4" role="alert">
      <%= flash[:notice] %>
   </div>
<% end %>

<% if flash[:alert] %>
   <div class="alert alert-danger mt-4" role="alert">
      <%= flash[:alert] %>
   </div>
<% end %>

app/views/shared/_form_errors.html.erb
  <% if form.object.errors.any? %>
     <div class="alert alert-danger">
        <% form.object.errors.full_messages.each do |message| %>
          <div><%= message %></div>
        <% end %>
     </div>
   <% end %> 

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
   <%= link_to "Navbar", root_path, class: "navbar-brand"  %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
       <ul class="navbar-nav">
         <li class="nav-item">
           <%= link_to "Tweets", tweets_path, class: "nav-link"  %>
         </li>
              <li class="nav-item">
           <%= link_to "Twitter Accounts", twitter_accounts_path, class: "nav-link"  %>
         </li>
         <li class="nav-item">
           <%= link_to "About", about_path, class: "nav-link"  %>
         </li>
      </ul>


      <ul class="d-flex align-items-center navbar-nav ms-auto mb-2 mb-lg-0 gap-3">
      <% if Current.user %>
     <div class="dropdown">
        <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
          Profile
      </button>
     <ul class="dropdown-menu">
           <%= link_to "Update Password", edit_password_path, class: "dropdown-item" %> 
       <li>
          <hr class="dropdown-divider">
       </li>
       <li class="dropdown-item disabled"><%= Current.user.email %></li>
     </ul>
    </div>
         <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary"  %>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", sign_in_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", sign_up_path, class: "nav-link"  %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>